---
# Crea l'utente ubuadmin con privilegi sudo
- name: Crea l'utente ubuadmin
  user:
    name: ubuadmin
    password: "$6$0ZoErgjbXG9y54dO$bZl6YSiy4ev3GvtCo.jPyP8wMvGuxWTLCF3sfFNwFkL8yv1K4fTIRwN9y6bJl2c04f0yYNE1tzYl7HGIQpLA51"
    shell: /bin/bash
    state: present
    create_home: yes

# Aggiungi ubuadmin al gruppo sudo
- name: Aggiungi ubuadmin al gruppo sudo
  user:
    name: ubuadmin
    groups: sudo
    append: yes
